

services:
  postgres:
    image: postgres:16-alpine
    container_name: stream_postgres
    environment:
      POSTGRES_USER: stream
      POSTGRES_PASSWORD: stream
      POSTGRES_DB: stream_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: stream_redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit
    container_name: stream_mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

volumes:
  postgres_data:
